### ISSUE TITLE
build-frontend fails without manually installing tailwindcss

### ISSUE THREAD

**Issue by AutumnSpark1226** [liamcottle/reticulum-meshchat#24]
```
npm run build-frontend

> reticulum-meshchat@1.14.0 build-frontend
> vite build

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.4.1 building for production...
<script src="assets/js/codec2-emscripten/c2enc.js"> in "/index.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/c2dec.js"> in "/index.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/sox.js"> in "/index.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/codec2-lib.js"> in "/index.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/wav-encoder.js"> in "/index.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/codec2-microphone-recorder.js"> in "/index.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/c2enc.js"> in "/call.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/c2dec.js"> in "/call.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/sox.js"> in "/call.html" can't be bundled without type="module" attribute
<script src="assets/js/codec2-emscripten/codec2-lib.js"> in "/call.html" can't be bundled without type="module" attribute
✓ 88 modules transformed.
x Build failed in 683ms
error during build:
[vite:css] Failed to load PostCSS config (searchPath: /home/user/reticulum-meshchat/src/frontend): [Error] Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /home/user/reticulum-meshchat/postcss.config.js

(@/home/user/reticulum-meshchat/postcss.config.js)
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /home/user/reticulum-meshchat/postcss.config.js

(@/home/user/reticulum-meshchat/postcss.config.js)
    at load (file:///home/user/reticulum-meshchat/node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:33591:11)
    at file:///home/user/reticulum-meshchat/node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:33616:16
    at Array.map (<anonymous>)
    at plugins (file:///home/user/reticulum-meshchat/node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:33615:8)
    at processResult (file:///home/user/reticulum-meshchat/node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:33685:14)
    at file:///home/user/reticulum-meshchat/node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:33815:14
file: /home/user/reticulum-meshchat/node_modules/vis-network/styles/vis-network.css
```

After manually installing tailwindcss (```npm install tailwindcss```) the frontend can be built successfully. It seems like the dependency is missing somewhere, so this should be an easy fix.

**Comment by liamcottle** [comment]
Hey! I thought this might catch someone out ;) I should've added a note in the release.

TailwindCSS was originally included as a static JS file from the assets folder (as a quick way to avoid a build step), but now that I've been using vite for a while, this has finally been migrated to being installed via npm and bundled with vite into the dist assets.

The `tailwindcss` dependency was already in the `package.json` you just needed to run `npm install` after doing a `git pull`.

Running `npm install tailwindcss` will also work, but it _might_ adjust your local `package.json` or `package-lock.json` if there happened to be a new version released.
